Several improvements (fast DH param generation, color msgs, less prompts).

diff --git a/setup-vpn b/setup-vpn
--- a/setup-vpn
+++ b/setup-vpn
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # setup-vpn: Install and configure OpenVPN server or client on Raspberry Pi
 #
@@ -44,57 +44,62 @@
 #	rm -rf robot-vpn
 
 #
-# Setup functions for each setup type start here; main script is at the end
+# Functions to print messages/prompts in color
 #
+msg() { echo -e "\e[1;34m$1\e[0m" 1>&2; }	# blue
+prompt() { echo -ne "\e[1;33m$1\e[0m" 1>&2; }	# yellow
+
+if [ $EUID -ne 0 ]; then
+    msg "[Re-executing with sudo to perform setup as root user]"
+    exec sudo "$0" "$@"
+fi
 
 #
-# Function to print highlighted (blue) message
+# Function to set up a VPN client
 #
-msg()
+setup_client()
 {
-    echo "\e[1;34m$1\e[0m" 1>&2
-}
+    case $SETUP_TYPE in
 
-#
-# Function to print highlighted (yellow) prompt message
-#
-prompt()
-{
-    echo -n "\e[1;33m$1\e[0m" 1>&2
-}
-
-#
-# Function to set up auxiliary VPN client
-#
-setup_aux_client()
-{
-    BRIDGE_IPADDR=$TEAM_NETWORK.252
-    prompt "Enter a unique static bridge IP address [$BRIDGE_IPADDR]: "
-    read REPLY
-    if [ "x$REPLY" != "x" ]; then
-	BRIDGE_IPADDR=$REPLY
-    fi
-
-    rm -rf $EDIR
-    cp -R /usr/share/easy-rsa $EDIR
+	ds)
+	    BRIDGE_IPADDR=$TEAM_NETWORK.253
+	    CLIENT_ID="DS_VPN_Client"
+	    ;;
+	robot)
+	    BRIDGE_IPADDR=$TEAM_NETWORK.251
+	    CLIENT_ID="Robot_VPN_Client"
+	    ;;
+	aux)
+	    BRIDGE_IPADDR=$TEAM_NETWORK.252
+	    CLIENT_ID="Aux_VPN_Client"
+	    ;;
+	*)
+	    msg "Bad client type: $SETUP_TYPE"
+	    exit 1
+	    ;;
+    esac
 
     #
     # Initialize PKI files
     #
+    rm -rf $EDIR
+    cp -R /usr/share/easy-rsa $EDIR
     cd $EDIR
     ./easyrsa init-pki
     mkdir pki/issued
 
     #
-    # Load auxiliary client configuration files from private Github repo
+    # Load client configuration files from private Github repo
     #
-    msg "Installing configuration files for auxiliary VPN client..."
-    cp $PI_HOME/robot-vpn/openvpn.conf-Aux_VPN_Client $VDIR/openvpn.conf
-    sed -i "s/robotvpn.domain.com/$SERVER_IPADDR/g" $VDIR/openvpn.conf
+    msg "Installing configuration files for $CLIENT_ID ..."
+    cp $PI_HOME/robot-vpn/openvpn.conf-$CLIENT_ID $VDIR/openvpn.conf
     cd $PI_HOME/$GITHUB_REPO
+    SERVER_IPADDR=`cat VPN_Server_ipaddr`
+    msg "Using server IP address $SERVER_IPADDR"
+    sed -i "s/robotvpn.domain.com/$SERVER_IPADDR/g" $VDIR/openvpn.conf
     cp ca.crt ta.key $PKIDIR
-    cp Aux_VPN_Client.crt $PKIDIR/issued
-    cp Aux_VPN_Client.key $PKIDIR/private
+    cp $CLIENT_ID.crt $PKIDIR/issued
+    cp $CLIENT_ID.key $PKIDIR/private
     cp $PI_HOME/robot-vpn/bridge.sh /etc/init.d/bridge
     sed -i "s/10.TE.AM.251/$BRIDGE_IPADDR/g" /etc/init.d/bridge
     sed -i "s/10.TE.AM/$TEAM_NETWORK/g" /etc/init.d/bridge
@@ -103,93 +108,7 @@ setup_aux_client()
     chmod a+rx /etc/init.d/bridge
     echo "denyinterfaces eth0" >> /etc/dhcpcd.conf
 
-    msg "Auxiliary VPN client successfuly set up"
-}
-
-#
-# Function to set up driver station VPN client
-#
-setup_ds_client()
-{
-    BRIDGE_IPADDR=$TEAM_NETWORK.253
-    prompt "Enter a unique static bridge IP address [$BRIDGE_IPADDR]: "
-    read REPLY
-    if [ "x$REPLY" != "x" ]; then
-	BRIDGE_IPADDR=$REPLY
-    fi
-
-    rm -rf $EDIR
-    cp -R /usr/share/easy-rsa $EDIR
-
-    #
-    # Initialize PKI files
-    #
-    cd $EDIR
-    ./easyrsa init-pki
-    mkdir pki/issued
-
-    #
-    # Load driver station client configuration files from private Github repo
-    #
-    msg "Installing configuration files for driver station VPN client..."
-    cp $PI_HOME/robot-vpn/openvpn.conf-DS_VPN_Client $VDIR/openvpn.conf
-    sed -i "s/robotvpn.domain.com/$SERVER_IPADDR/g" $VDIR/openvpn.conf
-    cd $PI_HOME/$GITHUB_REPO
-    cp ca.crt ta.key $PKIDIR
-    cp DS_VPN_Client.crt $PKIDIR/issued
-    cp DS_VPN_Client.key $PKIDIR/private
-    cp $PI_HOME/robot-vpn/bridge.sh /etc/init.d/bridge
-    sed -i "s/10.TE.AM.251/$BRIDGE_IPADDR/g" /etc/init.d/bridge
-    sed -i "s/10.TE.AM/$TEAM_NETWORK/g" /etc/init.d/bridge
-    rm -f /etc/rc2.d/S01bridge
-    ln -s ../init.d/bridge /etc/rc2.d/S01bridge
-    chmod a+rx /etc/init.d/bridge
-    echo "denyinterfaces eth0" >> /etc/dhcpcd.conf
-
-    msg "Driver station VPN client successfuly set up"
-}
-
-#
-# Function to set up robot VPN client
-#
-setup_robot_client()
-{
-    BRIDGE_IPADDR=$TEAM_NETWORK.251
-    prompt "Enter a unique static bridge IP address [$BRIDGE_IPADDR]: "
-    read REPLY
-    if [ "x$REPLY" != "x" ]; then
-	BRIDGE_IPADDR=$REPLY
-    fi
-
-    rm -rf $EDIR
-    cp -R /usr/share/easy-rsa $EDIR
-
-    #
-    # Initialize PKI files
-    #
-    cd $EDIR
-    ./easyrsa init-pki
-    mkdir pki/issued
-
-    #
-    # Load robot client configuration files from private Github repo
-    #
-    msg "Installing configuration files for robot VPN client..."
-    cp $PI_HOME/robot-vpn/openvpn.conf-Robot_VPN_Client $VDIR/openvpn.conf
-    sed -i "s/robotvpn.domain.com/$SERVER_IPADDR/g" $VDIR/openvpn.conf
-    cd $PI_HOME/$GITHUB_REPO
-    cp ca.crt ta.key $PKIDIR
-    cp Robot_VPN_Client.crt $PKIDIR/issued
-    cp Robot_VPN_Client.key $PKIDIR/private
-    cp $PI_HOME/robot-vpn/bridge.sh /etc/init.d/bridge
-    sed -i "s/10.TE.AM.251/$BRIDGE_IPADDR/g" /etc/init.d/bridge
-    sed -i "s/10.TE.AM/$TEAM_NETWORK/g" /etc/init.d/bridge
-    rm -f /etc/rc2.d/S01bridge
-    ln -s ../init.d/bridge /etc/rc2.d/S01bridge
-    chmod a+rx /etc/init.d/bridge
-    echo "denyinterfaces eth0" >> /etc/dhcpcd.conf
-
-    msg "Robot VPN client successfuly set up"
+    msg "$CLIENT_ID successfully set up"
 }
 
 #
@@ -197,6 +116,20 @@ setup_robot_client()
 #
 setup_server()
 {
+    #
+    # Prompt for VPN server IP address or host name
+    #
+    msg "The VPN server will be directly reachable on the Internet or"
+    msg "will be reachable through a router to its private (NAT) address."
+    msg "It must be a publicly reachable IP address or host name."
+
+    SERVER_IPADDR=none
+    prompt "Enter the VPN server IP address or host name [$SERVER_IPADDR]: "
+    read REPLY
+    if [ "x$REPLY" != "x" ]; then
+	SERVER_IPADDR=$REPLY
+    fi
+
     #
     # Prompt for SSL certificate identifiers
     # COUNTRY, STATE, CITY, ORG, EMAIL, and OU, e.g.:
@@ -215,7 +148,7 @@ setup_server()
     CITY="Eagan"
     ORG="EHS Robotics"
     EMAIL="ca@eaganrobotics.com"
-    OU="Team 2220"
+    OU="Team $TEAM_NUMBER"
 
     msg "The parameters you enter below will be used when forming the"
     msg "component values of the client and server certificates."
@@ -299,7 +232,9 @@ setup_server()
     # Generate Diffie-Hellman (DH) parameters file
     #
     msg "Generating Diffie-Hellman (DH) parameters file..."
-    ./easyrsa gen-dh
+    #./easyrsa gen-dh
+    openssl dhparam -dsaparam -out $PKIDIR/dh.pem 2048 || die "Failed to build DH params"
+    msg "DH parameters of size 2048 created"
 
     #
     # Generate a random key to be used as a shared secret
@@ -333,7 +268,8 @@ setup_server()
     cp $PKIDIR/ca.crt $PKIDIR/ta.key .
     cp $PKIDIR/issued/*_VPN_Client.crt .
     cp $PKIDIR/private/*_VPN_Client.key .
-    git add ca.crt ta.key *_VPN_Client.*
+    echo $SERVER_IPADDR > VPN_Server_ipaddr
+    git add ca.crt ta.key *_VPN_Client.* VPN_Server_ipaddr
     git commit --message="VPN client configuration files for Team $TEAM_NUMBER"
     git push
 
@@ -344,13 +280,9 @@ setup_server()
     cp $PI_HOME/robot-vpn/openvpn.conf-VPN_Server $VDIR/openvpn.conf
     sed -i "s/10.TE.AM/$TEAM_NETWORK/g" $VDIR/openvpn.conf
 
-cat << "EOF" 1>&2
-VPN server successfuly set up; you can now set up the VPN clients
-
-Note: Make sure to set up a port forwarding rule on your router
-that forwards UDP port 1194 to the IP address of the Raspberry Pi.
-
-EOF
+    msg "VPN server successfully set up; you can now set up the VPN clients"
+    msg "Note: Make sure to set up a port forwarding rule on your router"
+    msg "that forwards UDP port 1194 to the IP address of the Raspberry Pi."
 }
 
 #
@@ -364,17 +296,13 @@ VDIR=/etc/openvpn
 EDIR=$VDIR/easy-rsa
 PKIDIR=$EDIR/pki
 
-cat << "EOF" 1>&2
-
-OpenVPN server and client setup for Raspberry Pi for use with FRC robots
-
-In the following prompts, defaults are noted in square brackets []
-
-EOF
+msg "OpenVPN server and client setup for Raspberry Pi for use with FRC robots"
+msg "In the following prompts, defaults are noted in square brackets []"
 
 GITHUB_USER="my-user"
 GITHUB_TOKEN="none"
 GITHUB_REPO="my-vpn-files"
+TEAM_NUMBER="2220"
 
 #
 # Load previously saved VPN setup info, if any
@@ -384,7 +312,7 @@ if [ -f $SETUP_INFO ]; then
 fi
 
 #
-# Prompt for VPN setup info using loaded info as defaults
+# Prompt for VPN setup info and team number using loaded info as defaults
 #
 prompt "Enter your Github user name [$GITHUB_USER]: "
 read REPLY
@@ -404,12 +332,24 @@ if [ "x$REPLY" != "x" ]; then
     GITHUB_REPO=$REPLY
 fi
 
-msg "Saving Github info in $SETUP_INFO"
+prompt "Enter your team number [$TEAM_NUMBER]: "
+read REPLY
+if [ "x$REPLY" != "x" ]; then
+    TEAM_NUMBER=$REPLY
+fi
+
+msg "Saving VPN setup info in $SETUP_INFO"
 cat << EOF > $SETUP_INFO
 GITHUB_USER=$GITHUB_USER
 GITHUB_TOKEN=$GITHUB_TOKEN
 GITHUB_REPO=$GITHUB_REPO
+TEAM_NUMBER=$TEAM_NUMBER
 EOF
+
+#
+# Calculate the team subnet (10.TE.AM)
+#
+TEAM_NETWORK=10.`expr $TEAM_NUMBER / 100`.`expr $TEAM_NUMBER % 100`
 
 #
 # Clone the empty personal repository created earlier
@@ -425,7 +365,6 @@ else
     git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/$GITHUB_USER/$GITHUB_REPO
 fi
 
-
 if [ ! -d "$PI_HOME/$GITHUB_REPO" ]; then
     msg "Please run script again with proper user, token, and repository name"
     exit 1
@@ -437,53 +376,21 @@ fi
 #
 msg "Updating package index..."
 apt-get -y update
+
 msg "Installing newest versions of all packages..."
 apt-get -y upgrade
+
 msg "Installing required additional packages..."
 apt-get -y install openvpn unzip bridge-utils
+
 msg "Reconfiguring time zone data..."
 dpkg-reconfigure -u tzdata
 
 #
-# Prompt for team number and calculate team network prefix
-#
-TEAM_NUMBER=2220
-prompt "Enter your team number [$TEAM_NUMBER]: "
-read REPLY
-if [ "x$REPLY" != "x" ]; then
-    TEAM_NUMBER=$REPLY
-fi
-
-TEAM_NETWORK=10.`expr $TEAM_NUMBER / 100`.`expr $TEAM_NUMBER % 100`
-
-#
-# Prompt for VPN server IP address / host name
-#
-SERVER_IPADDR=none
-
-cat << "EOF" 1>&2
-
-The VPN server will either be directly reachable on the Internet or
-will be reachable through a router to its private (NAT) address.
-In either case, it must be a publicly reachable IP address or host name.
-
-EOF
-
-prompt "Enter the VPN server IP address or host name [$SERVER_IPADDR]: "
-read REPLY
-if [ "x$REPLY" != "x" ]; then
-    SERVER_IPADDR=$REPLY
-fi
-
-#
 # Prompt for VPN setup type
 #
-SETUP_TYPE=none
-prompt "Enter setup type (server, ds, robot, or aux) [$SETUP_TYPE]: "
-read REPLY
-if [ "x$REPLY" != "x" ]; then
-    SETUP_TYPE=$REPLY
-fi
+prompt "Enter setup type (server, ds, robot, or aux): "
+read SETUP_TYPE
 
 case $SETUP_TYPE in
 
@@ -491,16 +398,8 @@ case $SETUP_TYPE in
 	setup_server
 	;;
 
-    ds)
-	setup_ds_client
-	;;
-
-    robot)
-	setup_robot_client
-	;;
-
-    aux)
-	setup_aux_client
+    robot|ds|aux)
+	setup_client
 	;;
 
     *)
